src/web/SDS.WebApp.MVC/Models/ErrorViewModel.cs
namespace SDS.WebApp.MVC.Models
{
    public class ErrorViewModel
    {
        public int ErroCode { get; set; }
        public string Titulo { get; set; }
        public string Mensagem { get; set; }
    }

    public class ResponseResult
    {
        public string Title { get; set; }
        public int Status { get; set; }
        public ResponseErrorMessages Errors { get; set; }
    }

    public class ResponseErrorMessages
    {
        public List<string> Mensagens { get; set; }
    }
}

src/web/SDS.WebApp.MVC/Models/UsuarioViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SDS.WebApp.MVC.Models
{
    public class UsuarioRegistro
    {
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 6)]
        public string Senha { get; set; }

        [DisplayName("Confirme sua senha")]
        [Compare("Senha", ErrorMessage = "As senhas não conferem.")]
        public string SenhaConfirmacao { get; set; }
    }

    public class UsuarioLogin
    {
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 6)]
        public string Senha { get; set; }
    }

    public class UsuarioRespostaLogin
    {
        public string AccessToken { get; set; }
        public double ExpiresIn { get; set; }
        public UsuarioToken UsuarioToken { get; set; }
        public ResponseResult ResponseResult { get; set; }
    }

    public class UsuarioToken
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public IEnumerable<UsuarioClaim> Claims { get; set; }
    }

    public class UsuarioClaim
    {
        public string Value { get; set; }
        public string Type { get; set; }
    }
}

src/web/SDS.WebApp.MVC/Controllers/IdentidadeController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SDS.WebApp.MVC.Services;
using System.Security.Claims;
using SDS.WebApp.MVC.Models;
using System.IdentityModel.Tokens.Jwt;

namespace SDS.WebApp.MVC.Controllers
{
    public class IdentidadeController : MainController
    {
        private readonly IAutenticacaoService _autenticacaoService;

        public IdentidadeController(IAutenticacaoService autenticacaoService)
        {
            _autenticacaoService = autenticacaoService;
        }

        [HttpGet]
        [Route("nova-conta")]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [Route("nova-conta")]
        public async Task<IActionResult> Registro(UsuarioRegistro usuarioRegistro)
        {
            if (!ModelState.IsValid) return View(usuarioRegistro);

            var resposta = await _autenticacaoService.Registro(usuarioRegistro);

            if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioRegistro);

            await RealizarLogin(resposta);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("login")]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(UsuarioLogin usuarioLogin, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (!ModelState.IsValid) return View(usuarioLogin);

            var resposta = await _autenticacaoService.Login(usuarioLogin);

            if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioLogin);

            await RealizarLogin(resposta);

            if (string.IsNullOrEmpty(returnUrl)) return RedirectToAction("Index", "Home");

            return LocalRedirect(returnUrl);
        }

        [HttpGet]
        [Route("sair")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private async Task RealizarLogin(UsuarioRespostaLogin resposta)
        {
            var token = ObterTokenFormatado(resposta.AccessToken);

            var claims = new List<Claim>();
            claims.Add(new Claim("JWT", resposta.AccessToken));
            claims.AddRange(token.Claims);

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                IsPersistent = true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        private static JwtSecurityToken ObterTokenFormatado(string jwtToken)
        {
            return new JwtSecurityTokenHandler().ReadToken(jwtToken) as JwtSecurityToken;
        }
    }
}

src/web/SDS.WebApp.MVC/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using SDS.WebApp.MVC.Models;

namespace SDS.WebApp.MVC.Controllers
{
    public class MainController : Controller
    {
        protected bool ResponsePossuiErros(ResponseResult resposta)
        {
            if (resposta != null && resposta.Errors.Mensagens.Any())
            {
                foreach (var mensagem in resposta.Errors.Mensagens)
                {
                    ModelState.AddModelError(string.Empty, mensagem);
                }

                return true;
            }

            return false;
        }
    }
}

src/web/SDS.WebApp.MVC/Extensions/SummaryViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SDS.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

src/web/SDS.WebApp.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/web/SDS.WebApp.MVC/Views/Identidade/Login.cshtml
@model SDS.WebApp.MVC.Models.UsuarioLogin

@{
    ViewData["Title"] = "Login de usuário";
}


<section class="section-conten padding-y container" style="min-height:35vh">
    
    <vc:Summary></vc:Summary>

    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">
        
        <div class="card-body">
            <h4 class="card-title mb-4">Seja bem vindo!</h4>
            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                </div>
            </form>
        </div>
        <div class="card-footer text-center">Ainda não tem uma conta?<a asp-controller="Identidade" asp-action="Registro"> Criar uma conta</a></div>
    </div>

</section>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/web/SDS.WebApp.MVC/Views/Identidade/Registro.cshtml
@model SDS.WebApp.MVC.Models.UsuarioRegistro

@{
    ViewData["Title"] = "Registro de novo usuário";
}

<section class="section-conten padding-y container" style="min-height: 35vh">
    
    <vc:Summary></vc:Summary>

    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">

        <div class="card-body">
            <h4 class="card-title mb-4">Seja bem vindo!</h4>

            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

@*                 <div class="form-group">
                    <label asp-for="Nome"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Cpf"></label>
                    <input asp-for="Cpf" class="form-control" />
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div> *@

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="SenhaConfirmacao"></label>
                    <input type="password" asp-for="SenhaConfirmacao" class="form-control" />
                    <span asp-validation-for="SenhaConfirmacao" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                </div>
            </form>
        </div>
        <div class="card-footer text-center">Já tem uma conta?<a asp-controller="Identidade" asp-action="Login"> Entrar</a></div>
    </div>

</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/web/SDS.WebApp.MVC/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div style="padding-top: 15px;"></div>

    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="msgRetorno" style="padding-top: 20px">Opa! Algo deu errado :(</h3>
        <div style="padding-top: 20px" asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

src/web/SDS.WebApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewData["Title"] - SuperDemoStore Enterprise</title>
    
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
    <link href="~/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" />

</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-4">
                        <a asp-action="Index" asp-controller="Catalogo" class="brand-wrap">
                            <img alt="Nerd Store Enterprise" class="logo" src="~/images/logo.png">
                        </a>   
                    </div>
                    
                    <div class="col-lg-9 col-sm-7 col-8 order-2 order-lg-3">
                        <div class="d-flex justify-content-end">
                            <div style="padding-right: 15px">
                                <a href="#" class="widget-header">
                                    <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                                    <span class="badge badge-pill badge-danger notify">0</span>
                                </a>
                            </div>
                            <div>
                                <partial name="_LoginPartial" />
                            </div>
                        </div>   
                    </div>   
                </div>   
            </div>   
        </section>    



    </header>
    <div style="min-height: 625px;">
            @RenderBody()
    </div>

    <footer class="section-footer border-top">
        <div class="container">
            <section class="footer-top padding-y">
                <div class="row">
                    <aside class="col-md-4">
                        <article class="mr-3">
                            <img src="~/images/logo.png" class="logo-footer">
                            <p class="mt-3">Um pequeno texto institucional da Nerd Store Enterprise.</p>
                            <div>
                                <a class="btn btn-icon btn-light" title="Facebook" target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-icon btn-light" title="Instagram" target="_blank" href="#"><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-icon btn-light" title="Youtube" target="_blank" href="#"><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-icon btn-light" title="Twitter" target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                            </div>
                        </article>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Sobre</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Sobre nós</a></li>
                            <li> <a href="#">Serviços</a></li>
                            <li> <a href="#">Termo de Uso</a></li>
                            <li> <a href="#">FAQ</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Serviços</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Meus Pedidos</a></li>
                            <li> <a href="#">Meu Perfil</a></li>
                            <li> <a href="#">Cancelamentos</a></li>
                            <li> <a href="#">Reembolsos</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-2  col-md-2">
                        <h6 class="title">Mobile</h6>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/appstore.png" height="40"></a>
                        <a href="#" class="d-block mb-2"><img src="~/images/misc/playmarket.png" height="40"></a>
                    </aside>
                </div>   
            </section>	  

            <section class="footer-copyright border-top">
                <p class="float-left text-muted"> Nerd Store Enterprise </p>
                <p class="float-right text-muted">
                    Material do curso ASP.NET Core Enterprise Applications - 
                    <a target="_blank" href="https://desenvolvedor.io">desenvolvedor.io</a>
                </p>
            </section>
        </div>  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <script src="~/js/script.js" type="text/javascript"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>